import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     auth,
                                     children,
                                   }: Readonly<{
  children: ReactNode;
  auth: ReactNode
}>) {
  return (
    <html lang="en">
    <body>
    {auth}
    {children}
    </body>
    </html>
  );
}
