import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     foo,
                                     children,
                                   }: Readonly<{
  children: ReactNode;
  foo: ReactNode
}>) {
  return (
    <html lang="en">
    <body>

    <div className="flex justify-center mt-40 min-h-dvh">
      {children}
    </div>


    {foo}
    </body>
    </html>
  );
}
